### ISSUE TITLE
Smooth pinch with ResumableZoom

### ISSUE THREAD

**Issue by rrebase** [Glazzes/react-native-zoom-toolkit#10]
### Description

Hey, first of all wanted to say that you've done a fantastic job with this library 🙇‍♂️

Tried the `ResumableZoom` component and it works well, there's only two places where it "jitters" on iOS device. Did some investigation and here's what I found:
- When pinch is active and panning just a tiny bit then it "stutters". Traced it down to inaccurate `focalX` & `focalY` values on RNGH side https://github.com/software-mansion/react-native-gesture-handler/issues/2833
- When releasing a pinch, then it often jumps. Apparently there's a few updates that happen with one touch / finger instead of two. This leads to a significant change in focal point. Possible solution is to add a check [here](https://github.com/Glazzes/react-native-zoom-toolkit/blob/f692eb682d32ef40cc33db4789ba00a707dc9f13/src/commons/hooks/usePinchCommons.ts#L121) to only handle the update if `e.numberOfPointers === 2`

**Comment by Glazzes** [comment]
## The jittering
I tried simulating the problem with the focal point lack of decimal places by using Math.round, floor and ceil and they are responsible for the jittering as you mentioned.

For this issue I'm tied to whatever Software Mansion decides to do about this issue, there's very little I can do about it, however I'll look for a workaround in the mean time.

## Jump at the end of the pinch gesture
### Observations
You're right about assuming its caused by a single pointer triggering undesired updates, however the gesture triggering such updates is actually the pan gesture, however this activation's behaviour is abnormal because of the conditions that trigger it, from my perspective a couple of `onPanChange` callback updates appear to outrun `onPanEnd` callback, I actually fixed a way more severe error related to this one, by mixing some code that should be in `onPanEnd` to `onPanchange`, this line right [here](https://github.com/Glazzes/react-native-zoom-toolkit/blob/main/src/commons/hooks/usePanCommons.ts#L104), I assumed it was because I do not have a decent phone.

### What is the root cause of this issue?
All gestures are disabled automatically at the very beginning of `onPinchEnd` callback, it seems the pan gesture manages to activate as it's getting disabled and at the middle of the snapback animation of `ScaleMode.BOUNCE`, then it gets clamped right away by the `onPanChange` updates that outrun `onPandEnd`.

### Solution
Disable pan gesture at the beginning of pinch gesture so they can not collide with each other when pinch gesture ends, disabling pan gesture makes no effect to "pan with pinch feature" as pan gesture is not responsible for it. following this action seems to fix the jump issue, as I have not been able to replicate it anymore.

 I'm not able to obtain a single pointer with Pinch gesture, however I will add the pointer check to prevent any strange and undesired issues.

**Comment by Glazzes** [comment]
After many unsuccessful attempts to implement a workaround for this feature I could not make it work.

- Using a pan based approach with two pointers outputs the same focal point a pinch gesture does, however its behaviour is not reliable at all, produces sudden jumps and jittering.
- Using pan gesture's translationX and translationY value result in a displacement of the image that prevents it from being aligned with the user's interaction.
- Manual gestures can probably be an option, I managed to simulate the focal points position, however for the scale value the end result is an image that looks to be a two different places at the same time.

Best I can do at this point is to make panWithPinch an opt in feature for iOS users and warn them in the documentation until a release of Gesture Handler with your fix comes out.

You can test again wheter the jump issue has gone away with the new version [1.0.2-0](https://www.npmjs.com/package/react-native-zoom-toolkit/v/1.0.2-0).
