### ISSUE TITLE
Syncing state with ResumableZoom at the end of panWithPinch

### ISSUE THREAD

**Issue by stevengoldberg** [Glazzes/react-native-zoom-toolkit#14]
### What Would You Like to Know?

Hello, great work on this library! My use case is as follows: I want to use a `panWithPinch` gesture in the `ResumableZoom` component. At the end of the gesture, I want to sync global state with the zoom/pan state.

If I provide an `onPanEnd` and `onPinchEnd` callback, only the latter is called when the gesture is released. However, even with `panMode={PanMode.CLAMP}`, I am able to pan beyond the boundaries of the image while pinching. Is this the intended behavior?

The pan gets reset to the bounds after releasing the gesture, but only after `onPinchEnd` is called, so that won't work for my purpose.

I can update state from within `onGestureActive`, but this results in many unnecessary updates.

This use case seems like it would be resolved by either fixing `panWithPinch` so that it doesn't pan beyond bounds when `panMode` is clamped, or by providing an `onGestureEnd` callback, similar to `SnapbackZoom`. What do you think?

**Comment by Glazzes** [comment]
Thanks your for the kind comments 🤗.

### The panWithPinch feature
`panWithPinch` feature is 100% controlled by the pinch gesture, the pan gesture never activates when you make use of this feature, why you may ask? Having a simultaneous pinch and pan gesture produces a huge offsetting on the focal point which leads to a VERY VERY inaccurate gesture, so basically an unusable feature for any realistic scenario.

I will explain it in the docs, so people will not get confused about this feature.

### Out of bounds while panning
In terms of being able to "pan with pinch" beyond the bounds of the container, it is an intentional behaviour for the Y axis because of the nature of the algorithm I'm using, it can be clamped, however at the moment for me it will produce a sudden snap in the focal point leading to a not so pleasant user experience, may be a thing to take a look in the near future.

### Solution
In terms of your problem I never thought of something like it for `ResuambleZoom`'s feature set, but it makes a lot of sense to me to add such callback, may drop for the next release 👌🏼.

At the moment the best solution I can offer you is the following: add a time out to your state syncing
```jsx
import { ResumableZoom, type ResumableZoomType } from 'react-native-zoom-toolkit';

const ref = useRef<ResumableZoomType>();

const syncState = () => {
  const timeout  = setTimeout(() => {
   const zoomState = ref.current?.requestState();
   // update your state here
  
   clearTimeout(timeout);
  }, 350); // I use default Reanimated's timing config which uses a 300ms duration animation, and +50 just to be sure it works well
}

const onPinchEnd = () => syncState();
const onPanEnd = () => syncState();

<ResuambleZoom ref={ref} onPanEnd={onPanEnd}  onPinchEnd={onPinchEnd}>
  <SomeComponent />
</ResuambleZoom>

```

**Comment by Glazzes** [comment]
Version `1.1.0` has been released with `onGestureEnd` callback, give it a try.
