### ISSUE TITLE
[Question]:Support of onPress event under the ResumableZoom?

### ISSUE THREAD

**Issue by cwy11111** [Glazzes/react-native-zoom-toolkit#49]
### Summary

Hello, may I ask can I use component like Button which will have a onPress event under the component wrapped under ResumableZoom?

**Comment by Glazzes** [comment]
Hi there, no you can not use any pressable component within any of the components exposed by this library, you gotta use `onTap` callback property if you need some sort of touch handling, anyways I get this question asked frequently, but no one ever details their use case properly in order for me to give a possible solution.

Expanding on this one, you can not use them because of Gesture Handler will take over any touch events, nonetheless I've tried solutions to this issue but none of them have proven to be achievable to me, some simply do not work and other ones require me to break features I value more than this one.

**Comment by Glazzes** [comment]
@cwy11111 After a lot of testing I've managed to get it working, however I do not have an iOS device to test whether it works properly or not on such system, in case you've got one could you please run this [gist](https://gist.github.com/Glazzes/357201f74fbfaddb3e933f4c258c4878)? If you can, let me know if it works like the lib does. 

The gist tis the pinch implementation that should make it to the lib in the next release if everything works fine.

**Comment by Glazzes** [comment]
onPress support has been added in version 3.0.0
