### ISSUE TITLE
[Question]: resumable zoom on flatlist

### ISSUE THREAD

**Issue by pixelpilot67** [Glazzes/react-native-zoom-toolkit#59]
### Summary

Hi! I'm trying to use the resumable zoom on a FlatList  I can scroll outside the image but I can't scroll by swiping directly on the image. Is this possible?

**Comment by Glazzes** [comment]
ResumableZoom has a pan gesture attached to it and of course it will collide with the scroll of the Flatlist, ResumableZoom is not mean to used on a flatlist as is, it requires quite the effort to turn ResumableZoom into a gallery due to complexity involved in doing so.

It's difficult to tell whether your goals are achievable or not as you do not mention your use case in more detail.
