### ISSUE TITLE
[Feature]: Example on how to use this together with react-native-reanimated-carousel

### ISSUE THREAD

**Issue by markwitt1** [Glazzes/react-native-zoom-toolkit#64]
### Summary

What would be the best way to combine this together with a carousel component from react-native-reanimated-carousel?

**Comment by Glazzes** [comment]
The only compatible component with that library would be `SnapbackZoom` because it does not have a pan gesture attached to it, talking of `ResumableZoom` component it's possible to mix such component with scrollable components like Flatlist (with some effort), however the library you mention does not provide a proper way of setting the scroll value programmatically.

This is not an enhancement, it's a question.

**Comment by markwitt1** [comment]
Thanks for the quick response! Could you give me a link to an example of the gallery being combined (for example via a modal that opens) with a horizontal FlatList?

**Comment by Glazzes** [comment]
@markwitt1 Can you explain your use case in more detail? I didn't understand what you mean, I mean the modal part is kind of irrelevant.
